services:
  web:
    build: .
    command: /entrypoint.sh
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/django_db
    depends_on:
      - db
    healthcheck:
      disable: true
    volumes:
      - .:/app

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  lighthouse:
#    build: ./lighthouse
#    depends_on:
#      - web
#    volumes:
#      - ./lighthouse/lighthouserc.json:/app/lighthouserc.json
#      - ./lighthouse/reports:/app/reports

  imgproxy:
    image: darthsim/imgproxy:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      IMGPROXY_BIND: ":8080"
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      IMGPROXY_ALLOWED_SOURCES: "*"
      IMGPROXY_ALLOW_INSECURE_SOURCE: "true"

volumes:
  postgres_data:
