services:
  web:
    build: .
    command: /entrypoint.sh
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/django_db
    depends_on:
      - db
        # condition: service_healthy
    healthcheck:
      disable: true
      # test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      # interval: 5s
      # timeout: 3s
      # retries: 3
    volumes:
      - .:/app

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  lighthouse:
    build: ./lighthouse
    depends_on:
      - web
        # condition: service_healthy
    command: >
      lighthouse http://web:8000
      --config-path=/app/lighthouserc.json
      --output=html
      --output-path=/app/reports/report.html
      --chrome-flags="--headless --no-sandbox"
    volumes:
      - ./lighthouse/lighthouserc.json:/app/lighthouserc.json
      - ./lighthouse/reports:/app/reports

volumes:
  postgres_data:
